server:
  name: "joona"
  http:
    address: ":10002"
  debug: 0
  url: "http://localhost:10002"

toggle:
  enable_something: true

environment:
  is_local: true
  is_debug: true
  einhorn_fds: 3

roles:
  developer: 1
  admin: 2
  user: 3
  public: 999999

route_roles:
  "":
    roles:
      - id: 1
        name: "Developer"
      - id: 2
        name: "Admin"
      - id: 3
        name: "Customer"
      - id: 4
        name: "PIC"
      - id: 5
        name: "Owner"
      - id: 6
        name: "User"

  "POST /v1/users/register":
    roles:
      - id: 999999
        name: "Public"

      