name: Unit Test and Deploy

on:
  push:
    branches:
      - release

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      
      - name: Build
        run: go build -o joona ./cmd/

      - name: Run Unit Tests
        run: go test ./...

      - name: Deploy to Azure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH }}
          script: |
            set -e
            cd /home/eifzed/joona
            git pull
            /usr/local/go/bin/go build -ldflags "-X main.CommitHash=$(git rev-parse --short HEAD)" -o joona ./cmd/
            cp ./joona /usr/bin
            cp -R ./files/etc/* /etc/apollo/
            systemctl restart joona.service