name: Unit Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Run Unit Tests
      run: |
        go test ./...
        if [ $? -eq 0 ]; then
          echo "Unit tests passed"
          echo "::set-output name=status::success"
        else
          echo "Unit tests failed"
          echo "::set-output name=status::failure"
        fi
        
    - name: Set status
      id: set-status
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const status = '${{ steps.test.outputs.status }}';
          github.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: status === 'success' ? 'success' : 'failure',
            context: 'Unit Test'
          });